[server]
hostname = "external"
server_role = "gateway-worker"
node_ip = "0.0.0.0"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://stack-storedata-1:3306/WSO2SHARED_DB?useSSL=false"
username = "admin"
password = "admin"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[apim.key_manager]
service_url = "https://stack-key-1:9443/services/"
username= "admin"
password= "admin"

[apim.event_hub]
enable = true
username = "admin"
password = "admin"
service_url = "https://stack-apim-1:9443/services/"
event_listening_endpoints = ["tcp://stack-apim-1:5672"]

[apim.cache.gateway_token]
enable = true
expiry_time = 15

[apim.cache.resource]
enable = true

[apim.cache.jwt_claim]
enable = true
expiry_time = 900

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","Channel","Content-Type","Device-Info","Session-Id","Correlation-Id","Caller-Id","Timestamp","Step-Up-Token","Delivery-Method","sessionId","appCode","Send-to","Pragma","Expires","User-Agent","Conversation-Id","x-datadog-origin","x-datadog-parent-id","x-datadog-sampled","x-datadog-sampling-priority","x-datadog-trace-id","maintenance-mode","x-amzn-waf-PartnerId","ot-baggage-channel"]
allow_credentials = false

[apim.throttling]
username= "admin"
password= "admin"
service_url = "https://stack-apim-1:9443/services/"
throttle_decision_endpoints = ["tcp://stack-apim-1:5672"]
enable_unlimited_tier = true
enable_header_based_throttling = false
enable_jwt_claim_based_throttling = false
enable_query_param_based_throttling = false

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://stack-apim-1:9611"]
traffic_manager_auth_urls = ["ssl://stack-apim-1:9711"]

[transport.http]
port = 8280

[transport.https]
port = 8243

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]