[server]
hostname = "localhost"
node_ip = "0.0.0.0"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
serverDetails = "WSO2 IS 5.10.0"
server_role = "key-manager"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[transport.https]
port = 9443

[transport.http]
port = 9763 

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://stack-storedata-1:3306/WSO2AM_DB?useSSL=false"
username = "admin"
password = "admin"
pool_options.maxActive=200
pool_options.testOnBorrow=true
pool_options.defaultAutoCommit=false
pool_options.defaultTransactionIsolation="READ_COMMITTED"
#apply wso2 suggested configs
maxWait = "60000"
minIdle = "5"
validationQuery="SELECT 1"
validationInterval="30000"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://stack-storedata-1:3306/WSO2SHARED_DB?useSSL=false"
username = "admin"
password = "admin"
pool_options.maxActive=200
pool_options.testOnBorrow=true
pool_options.defaultAutoCommit=false
pool_options.defaultTransactionIsolation="READ_COMMITTED"
#apply wso2 suggested configs
maxWait = "60000"
minIdle = "5"
validationQuery="SELECT 1"
validationInterval="30000"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://stack-storedata-1:3306/WSO2AM_DB?useSSL=false"
username = "admin"
password = "admin"
pool_options.maxActive=200
pool_options.testOnBorrow=true
pool_options.defaultAutoCommit=false
pool_options.defaultTransactionIsolation="READ_COMMITTED"
#apply wso2 suggested configs
maxWait = "60000"
minIdle = "5"
validationQuery="SELECT 1"
validationInterval="30000"

[keystore.primary]
file_name =  "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[keystore.internal]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[system.parameter]
"org.wso2.CipherTransformation"="RSA/None/NoPadding"

[encryption]
key = "CryptoService.Secret"

[event.default_listener]
scim2.enable=true

[user_store.properties]
SCIMEnabled=true
CaseInsensitiveUsername=false
UseCaseSensitiveUsernameForCacheKeys=false
UserNameAttribute= "uid"
UserIDAttribute= "saId"
GroupNameSearchFilter= "(&amp;(objectClass=groupOfNames)(cn=?))"
UserNameSearchFilter= "(&amp;(objectClass=person)(uid=?))"
UserIdSearchFilter= "(&amp;(objectClass=person)(uid=?))"

[admin_service.wsdl]
enable = "true"

[session_data.persistence]
enable_user_session_mapping = false
enable_persistence = false
persist_temporary_data = false

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

[event_listener.properties]
notification_endpoint = "https://stack-apim-1:9443/internal/data/v1/notify"
username = "admin"
password = "admin"
'header.X-WSO2-KEY-MANAGER' = "WSO2-IS"

[[resource.access_control]]
context = "(.)/keymanager-operations/user-info/claims(.)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/user-info/claims/generate"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/create"
scopes = "internal_application_mgt_create"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/applicationmgt/view"
scopes = "internal_application_mgt_view"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "PUT"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "DELETE"
permissions = "/permission/admin/manage/identity/applicationmgt/delete"
scopes = "internal_application_mgt_delete"

[tenant_context.rewrite]
custom_webapps = ["/keymanager-operations/"]

[transport.https.properties]
maxThreads="1000"
minSpareThreads="300"
disableUploadTimeout="false"
enableLookups="false"
connectionUploadTimeout="120000"
maxKeepAliveRequests="600"
acceptCount="600"
#wso2 recommendations
maxHttpHeaderSize = 131072

[oidc]
issuer = "https://stack-key-1:9445/oauth2"

[tasks]
client_dispatch_address = "https://$ref{server.hostname}:9448"
server_address = "https://stack-apim-1:9443"

[cors]
allow_generic_http_requests = true
allow_any_origin = true
allow_subdomains = true
support_any_header = true
supports_credentials = true

[oauth.extensions]
enable_token_binding = true